[package]
name = "ditherlib"
version = "0.6.0"
edition = "2024"
description = "Non-destructive image effects and dithering for whole images and polygon selections"
documentation = "https://docs.rs/ditherlib"
license = "Apache-2.0"
repository = "https://github.com/Downmoto/ditherlib"
homepage = "https://github.com/Downmoto/ditherlib"
readme = "README.md"
keywords = ["dithering", "image-processing", "image-effects", "graphics"]
categories = ["multimedia::images", "graphics", "algorithms"]
exclude = ["/*.jpg", "assets/", "tests/fixtures"]

[features]
default = ["jpeg", "png"]
avif = ["image/avif"]
bmp = ["image/bmp"]
dds = ["image/dds"]
exr = ["image/exr"]
ff = ["image/ff"]
gif = ["image/gif"]
hdr = ["image/hdr"]
ico = ["image/ico"]
jpeg = ["image/jpeg"]
png = ["image/png"]
pnm = ["image/pnm"]
qoi = ["image/qoi"]
tga = ["image/tga"]
tiff = ["image/tiff"]
webp = ["image/webp"]

[dependencies]
image = { version = "0.25.10", default-features = false }
